# Generated by Django 5.2.13 on 2026-04-25 17:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('tipo_banco', models.CharField(choices=[('PRIVADO', 'Privado'), ('GOBIERNO', 'Gobierno')])),
                ('direccion', models.CharField()),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField()),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('nacionalidad', models.CharField()),
                ('direccion', models.CharField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField()),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Natural'), ('JURIDICO', 'Jurídico')])),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='core.banco')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('pago_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pago_maximo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo_meses', models.PositiveIntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_credito', models.CharField(choices=[('AUTOMOTRIZ', 'Automotriz'), ('HIPOTECARIO', 'Hipotecario'), ('COMERCIAL', 'Comercial')])),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='créditos', to='core.banco')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='créditos', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
